

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3307:3306"
    volumes:
      - mysql-data-dev:/var/lib/mysql
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"    # c·ªïng ƒë·ªÉ microservices k·∫øt n·ªëi
      - "15672:15672"  # c·ªïng giao di·ªán web
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER:-admin}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS:-admin}
    networks:
      - app-network

    # ==========================
    # üçÉ MongoDB
    # ==========================
  mongodb:
    image: mongo:7.0
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongo-data-dev:/data/db
    networks:
      - app-network

  # ==========================
  # üåø Mongo Express
  # ==========================
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: always
    ports:
      - "8083:8081"
    environment:

      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123

    depends_on:
      - mongodb
    networks:
      - app-network


  authservice:
    build:
      context: ./services/AuthService
      dockerfile: Dockerfile.dev
    container_name: authservice
    ports:
      - "8081:8080"
    depends_on:
      - mysql-db
    volumes:
      - ./services/AuthService/src:/app/src
      - ./services/AuthService/pom.xml:/app/pom.xml
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/${MYSQL_DATABASE}?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Ho_Chi_Minh
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SERVER_PORT: 8080
      JWT_SECRET: ${JWT_SECRET}
      TZ: ${TZ}
    networks:
      - app-network

  inventoryservice:
    build:
      context: ./services/InventoryService
      dockerfile: Dockerfile.dev
    container_name: inventoryservice
    ports:
      - "8082:8080"
    depends_on:
      - mysql-db
    volumes:
      - ./services/InventoryService/src:/app/src
      - ./services/InventoryService/pom.xml:/app/pom.xml
      - ~/.m2/repository:/root/.m2/repository

    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/${MYSQL_DATABASE}?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Ho_Chi_Minh
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SERVER_PORT: 8080
      JWT_SECRET: ${JWT_SECRET}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
      TZ: ${TZ}
    networks:
      - app-network

# orderservice

  orderservice:
    build:
      context: ./services/OrderService
      dockerfile: Dockerfile.dev
    container_name: orderservice
    ports:
      - "8084:8080"
    depends_on:
      - mysql-db
    volumes:
      - ./services/OrderService/src:/app/src
      - ./services/OrderService/pom.xml:/app/pom.xml
      - ~/.m2/repository:/root/.m2/repository

    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/${MYSQL_DATABASE}?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Ho_Chi_Minh
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SERVER_PORT: 8080
      JWT_SECRET: ${JWT_SECRET}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
      TZ: ${TZ}
    networks:
      - app-network

  customerservice:
    build:
      context: ./services/CustomerService
      dockerfile: Dockerfile.dev
    container_name: customerservice
    ports:
      - "8085:8080"
    depends_on:
      - mongodb
    volumes:
      - ./services/CustomerService/src:/app/src
      - ./services/CustomerService/pom.xml:/app/pom.xml
      - ~/.m2/repository:/root/.m2/repository
    environment:
      SERVER_PORT: 8080
      JWT_SECRET: ${JWT_SECRET}
      TZ: ${TZ}
      SPRING_DATA_MONGODB_URI: ${SPRING_DATA_MONGODB_URI}
    networks:
      - app-network

  paymentservice:
    build:
      context: ./services/PaymentService
      dockerfile: Dockerfile.dev
    container_name: paymentservice
    ports:
      - "8088:8080"
    depends_on:
      - mysql-db
    volumes:
      - ./services/PaymentService/src:/app/src
      - ./services/PaymentService/pom.xml:/app/pom.xml
      - ~/.m2/repository:/root/.m2/repository

    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/${MYSQL_DATABASE}?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Ho_Chi_Minh
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SERVER_PORT: 8080
      JWT_SECRET: ${JWT_SECRET}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
      TZ: ${TZ}
    networks:
      - app-network



  notificationservice:
    build:
      context: ./services/NotificationService
      dockerfile: Dockerfile.dev
    container_name: notificationservice
    ports:
      - "8888:8888"
    depends_on:
      - mysql-db
    volumes:
      - ./services/NotificationService/src:/app/src
      - ./services/NotificationService/pom.xml:/app/pom.xml
      - ~/.m2/repository:/root/.m2/repository
    environment:
      SERVER_PORT: 8888
      JWT_SECRET: ${JWT_SECRET}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
      TZ: ${TZ}
    networks:
      - app-network

  apigateway:
    build:
      context: ./services/APIGateWay
      dockerfile: Dockerfile.dev
    container_name: apigateway
    ports:
      - "8080:8080"
    depends_on:
      - authservice
      - inventoryservice
      - orderservice
      - customerservice
      - paymentservice
    volumes:
      - ./services/APIGateWay/src:/app/src
      - ./services/APIGateWay/pom.xml:/app/pom.xml
    environment:
      SERVER_PORT: 8080
      JWT_SECRET: ${JWT_SECRET}
      TZ: ${TZ}
    networks:
      - app-network

  adminer:
    image: adminer:latest
    container_name: adminer
    depends_on:
      - mysql-db
    environment:
      - ADMINER_DEFAULT_SERVER=mysql-db
    ports:
      - "8086:8080"
    networks:
      - app-network

volumes:
  mysql-data-dev:
    name: mysql-data-dev
  mongo-data-dev:
    name: mongo-data-dev


networks:
  app-network:
    driver: bridge
