version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3307:3306"
    volumes:
      - mysql-data-dev:/var/lib/mysql
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"    # cổng để microservices kết nối
      - "15672:15672"  # cổng giao diện web
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER:-admin}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS:-admin}
    networks:
      - app-network

  authservice:
    build:
      context: ./services/AuthService
      dockerfile: Dockerfile.dev
    container_name: authservice
    ports:
      - "8081:8080"
    depends_on:
      - mysql-db
    volumes:
      - ./services/AuthService/src:/app/src
      - ./services/AuthService/pom.xml:/app/pom.xml
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/${MYSQL_DATABASE}?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Ho_Chi_Minh
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SERVER_PORT: 8080
      JWT_SECRET: ${JWT_SECRET}
      TZ: ${TZ}
    networks:
      - app-network

  inventoryservice:
    build:
      context: ./services/InventoryService
      dockerfile: Dockerfile.dev
    container_name: inventoryservice
    ports:
      - "8082:8080"
    depends_on:
      - mysql-db
    volumes:
      - ./services/InventoryService/src:/app/src
      - ./services/InventoryService/pom.xml:/app/pom.xml
      - ~/.m2/repository:/root/.m2/repository

    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/${MYSQL_DATABASE}?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Ho_Chi_Minh
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SERVER_PORT: 8080
      JWT_SECRET: ${JWT_SECRET}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
      TZ: ${TZ}
    networks:
      - app-network

  apigateway:
    build:
      context: ./services/APIGateWay
      dockerfile: Dockerfile.dev
    container_name: apigateway
    ports:
      - "8080:8080"
    depends_on:
      - authservice
      - inventoryservice
    volumes:
      - ./services/APIGateWay/src:/app/src
      - ./services/APIGateWay/pom.xml:/app/pom.xml
    environment:
      SERVER_PORT: 8080
      JWT_SECRET: ${JWT_SECRET}
      TZ: ${TZ}
    networks:
      - app-network

  adminer:
    image: adminer:latest
    container_name: adminer
    depends_on:
      - mysql-db
    environment:
      - ADMINER_DEFAULT_SERVER=mysql-db
    ports:
      - "8086:8080"
    networks:
      - app-network

volumes:
  mysql-data-dev:
    name: mysql-data-dev

networks:
  app-network:
    driver: bridge
