version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  authservice:
    build:
      context: ./services/AuthService
      dockerfile: Dockerfile
    container_name: authservice
    volumes:
      - ./services/AuthService:/workspace
    command: ./mvnw spring-boot:run
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/${MYSQL_DATABASE}?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Ho_Chi_Minh
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      TZ: ${TZ}
    depends_on:
      - mysql-db
    networks:
      - app-network

  inventoryservice:
    build:
      context: ./services/InventoryService
      dockerfile: Dockerfile
    container_name: inventoryservice
    volumes:
      - ./services/InventoryService:/workspace
    command: ./mvnw spring-boot:run
    ports:
      - "8082:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/${MYSQL_DATABASE}?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Ho_Chi_Minh
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
      TZ: ${TZ}
    depends_on:
      - mysql-db
    networks:
      - app-network

  apigateway:
    build:
      context: ./services/APIGateWay
      dockerfile: Dockerfile
    container_name: apigateway
    volumes:
      - ./services/APIGateWay:/workspace
    command: ./mvnw spring-boot:run
    ports:
      - "8080:8080"
    depends_on:
      - authservice
      - inventoryservice
    environment:
      JWT_SECRET: ${JWT_SECRET}
      TZ: ${TZ}
    networks:
      - app-network

  adminer:
    image: adminer:latest
    container_name: adminer
    depends_on:
      - mysql-db
    environment:
      - ADMINER_DEFAULT_SERVER=mysql-db
    ports:
      - "8086:8080"
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge
