spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: http://localhost:8081
              predicates:
                - Path=/api/auth/**

            - id: inventory-service
              uri: http://localhost:8082
              predicates:
                - Path=/api/inventory/**

            - id: customer-service
              uri: http://localhost:8090
              predicates:
                - Path=/api/customer/**

            - id: order-service
              uri: http://localhost:8084
              predicates:
                - Path=/api/order/**

            - id: payment-service
              uri: http://localhost:8085
              predicates:
                - Path=/api/payment/**

            - id: notification-service
              uri: http://localhost:8086
              predicates:
                - Path=/api/notification/**

            - id: reporting-service
              uri: http://localhost:8087
              predicates:
                - Path=/api/reporting/**
jwt:
  secret: "VExzN0s2V3p5R2Q1eXJzM29IVG95MFRhUG5nMUFzV1pCenFhWkYxclR0T29rUjJvT3pYckQ0UHVtN09uSjlSNEQxQ0FpY1BicHlCbmJsdmE1c293M01LQXlKMGZ5MXU="

server:
  port: 8080
