spring:
  application:
    name: notification-service
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_DEFAULT_USER}
    password: ${RABBITMQ_DEFAULT_PASS}


  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  address: 0.0.0.0
  port: 8888
  application:
    name: notification-service

