spring:
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}
  main:
    allow-bean-definition-overriding: true

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    org.mongodb.driver.connection: INFO

server:
  address: 0.0.0.0
  port: ${SERVER_PORT:8080}
  application:
    name: customer-service

