#spring:
#  data:
#    mongodb:
#      uri: mongodb://${MONGO_USER}:${MONGO_PASS}@${MONGO_HOST}:${MONGO_PORT}/${MONGO_DB}?authSource=admin
#
#  application:
#    name: customer-service
#
#server:
#  port: 8083
spring:
  data:
    mongodb:
      uri: mongodb://admin:admin123@localhost:27017/${MONGO_DB}?authSource=admin
      database: ${MONGO_DB}

  # Nếu bạn muốn logging rõ hơn khi kết nối
  main:
    allow-bean-definition-overriding: true

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    org.mongodb.driver.connection: INFO

server:
  port: 8090
